version: '2'

services:
  starter-api:
    container_name: starter-api
    image: starter-api
    volumes:
      - ./logs:/app/logs
    working_dir: /app
    command: python manage.py runserver -t 0.0.0.0 -p 5000
    ports:
      - "5000:5000"
    links:
      - postgres:postgres
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres
    image: db/postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=starter
    volumes_from:
      - postgres_data
    ports:
      - "5432:5432"
    depends_on:
      - postgres_data

  postgres_data:
    container_name: postgres_data
    image: db/postgres_datastore
