version: '2'

services:
  starter-api:
    container_name: starter-api
    image: starter/starter-api
    volumes:
      - ./logs:/app/logs
    working_dir: /app
    command: python manage.py runserver -t 0.0.0.0 -p 5000
    ports:
      - "5000:5000"
    links:
      - starter-postgres:starter-postgres
    depends_on:
      - starter-postgres
  
  starter-postgres:
    container_name: starter-postgres
    image: starter/postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=starter
    volumes_from:
      - starter-postgres_data
    ports:
      - "5432:5432"
    depends_on:
      - starter-postgres_data

  starter-postgres_data:
    container_name: starter-postgres_data
    image: starter/postgres_datastore
