@startuml Starter_Microservices_Deployment

node "<<executionEnvironment>>\nAPI Service - Flask/Python\nimage_name: starter/starter-api" as API #orange {
}

node "<<executionEnvionment>>\nDB Server - PosgreSQL\nimage_name: starter/postgres" as DB #orange {
}

node "<<device>>\nDB Volume - Persistence\nimage_name: starter/postgres_datastore" as Volume #cyan {
}

note right of API
docker run -d -t
    -v `pwd`/logs:/app/logs
    --name starter-api
    --link postgres:postgres
    -p 5000:5000 starter/starter-api
endnote

note right of DB
docker run -d
    -e POSTGRES_USER=admin
    -e POSTGRES_PASSWORD=admin
    -e POSTGRES_DB=starter
    --volumes-from starter-postgres_data
    --name starter-postgres
    -p 5432:5432 starter/postgres
endnote

note right of Volume
docker run -i -t
    --name starter-postgres_data
    starter/postgres_datastore
endnote

API --> DB
DB --> Volume

@enduml